#!/bin/bash

SOURCE="nuts333.c"

BINARY="nuts333"

FLAGS="-lcrypt -Wall -Wextra -Wformat=2 -Wmisleading-indentation -Wpedantic"

DEPS="ccache gcc"

for d in ${DEPS} ; do
  [ ! -x "$(which ${d}  2>/dev/null)" ] && { echo "${d}: missing" ; exit 1 ; }
done

ccache gcc ${SOURCE} -o ${BINARY} ${FLAGS}
